"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Loader2, Database, AlertCircle, Info, Settings, Link, Copy } from "lucide-react"
import { getDetailedErrorInfo } from "@/lib/error-translator"
import { buildRedisUri, generateConnectionName, type RedisConfig } from "@/lib/redis-uri"

interface ConnectionConfigProps {
  onConnect: (config: RedisConfig, connectionName?: string) => Promise<void>
}

export function ConnectionConfig({ onConnect }: ConnectionConfigProps) {
  const [config, setConfig] = useState<RedisConfig>({
    host: "localhost",
    port: 6379,
    username: "",
    password: "",
    database: 0,
    tls: false,
    connectTimeout: 10000,
    commandTimeout: 5000,
    maxRetriesPerRequest: 5,
  })
  const [connectionName, setConnectionName] = useState("")
  const [isConnecting, setIsConnecting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [detailedError, setDetailedError] = useState<any>(null)
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [connectionUri, setConnectionUri] = useState("")
  const [connectionMethod, setConnectionMethod] = useState<"form" | "uri">("form")

  const handleConnect = async () => {
    setIsConnecting(true)
    setError(null)
    setDetailedError(null)

    try {
      if (connectionMethod === "uri") {
        // For URI connections, we'll pass the URI directly
        const finalName = connectionName || getAutoGeneratedName()
        await onConnect({ uri: connectionUri } as any, finalName)
      } else {
        // For form connections, use the config object
        const finalName = connectionName || getAutoGeneratedName()
        await onConnect(config, finalName)
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Failed to connect to Redis"
      const detailed = getDetailedErrorInfo(errorMessage)
      setError(detailed.message)
      setDetailedError(detailed)
    } finally {
      setIsConnecting(false)
    }
  }

  const generateUri = () => {
    try {
      const uri = buildRedisUri(config)
      setConnectionUri(uri)
      setConnectionMethod("uri")
    } catch (error) {
      setError("Failed to generate URI: " + (error instanceof Error ? error.message : "Unknown error"))
    }
  }

  const getAutoGeneratedName = () => {
    if (connectionMethod === "uri" && connectionUri) {
      try {
        // Parse URI to get config for name generation
        const url = new URL(connectionUri)
        const uriConfig: RedisConfig = {
          host: url.hostname,
          port: parseInt(url.port) || (url.protocol === 'rediss:' ? 6380 : 6379),
          tls: url.protocol === 'rediss:',
          username: url.username || undefined,
          password: url.password || undefined,
          database: url.pathname && url.pathname !== '/' ? parseInt(url.pathname.slice(1)) : undefined,
        }
        return generateConnectionName(uriConfig)
      } catch (error) {
        console.warn('Failed to parse URI for name generation:', error)
        // Try to extract a basic name from the URI string
        const match = connectionUri.match(/(?:redis[s]?:\/\/)?(?:[^@]+@)?([^:\/]+)/)
        if (match && match[1]) {
          return `${match[1]} Redis`
        }
        return "Redis Connection"
      }
    }
    return generateConnectionName(config)
  }

  const copyUri = async () => {
    try {
      await navigator.clipboard.writeText(connectionUri)
    } catch (error) {
      console.error("Failed to copy URI:", error)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Database className="w-5 h-5" />
          Connect to Redis
        </CardTitle>
        <CardDescription>Enter your Redis connection details</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">

        <div className="space-y-2">
          <Label htmlFor="connectionName">Connection Name (optional)</Label>
          <Input
            id="connectionName"
            value={connectionName}
            onChange={(e) => setConnectionName(e.target.value)}
            placeholder="My Redis Server"
          />
          {!connectionName && ((config.host || config.port) || (connectionMethod === "uri" && connectionUri)) && (
            <div className="text-xs text-muted-foreground bg-muted/50 p-2 rounded border-l-2 border-blue-500">
              <div className="flex items-center gap-1">
                <Info className="w-3 h-3" />
                <span className="font-medium">Auto-generated name:</span>
              </div>
              <div className="mt-1 font-mono text-blue-600 dark:text-blue-400">
                {getAutoGeneratedName()}
              </div>
            </div>
          )}
        </div>

        <Tabs value={connectionMethod} onValueChange={(value) => setConnectionMethod(value as "form" | "uri")}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="form">Form</TabsTrigger>
            <TabsTrigger value="uri">URI</TabsTrigger>
          </TabsList>
          
          <TabsContent value="form" className="space-y-4">

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="host">Host</Label>
            <Input
              id="host"
              value={config.host}
              onChange={(e) => setConfig({ ...config, host: e.target.value })}
              placeholder="your-redis-server.com or 1.2.3.4"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="port">Port</Label>
            <Input
              id="port"
              type="number"
              value={config.port}
              onChange={(e) => setConfig({ ...config, port: Number.parseInt(e.target.value) || 6379 })}
              placeholder="6379"
            />
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="username">Username (optional)</Label>
          <Input
            id="username"
            value={config.username}
            onChange={(e) => setConfig({ ...config, username: e.target.value })}
            placeholder="Enter username if required"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="password">Password (optional)</Label>
          <Input
            id="password"
            type="password"
            value={config.password}
            onChange={(e) => setConfig({ ...config, password: e.target.value })}
            placeholder="Enter password if required"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="database">Database (optional)</Label>
          <Input
            id="database"
            type="number"
            value={config.database}
            onChange={(e) => setConfig({ ...config, database: Number.parseInt(e.target.value) || 0 })}
            placeholder="0"
          />
        </div>

        <div className="flex items-center space-x-2">
          <Switch
            id="tls"
            checked={config.tls}
            onCheckedChange={(checked) => setConfig({ ...config, tls: checked })}
          />
          <Label htmlFor="tls">Enable TLS/SSL (required for most cloud providers)</Label>
        </div>

        <div className="flex items-center space-x-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => setShowAdvanced(!showAdvanced)}
            className="flex items-center gap-2"
          >
            <Settings className="w-4 h-4" />
            {showAdvanced ? "Hide" : "Show"} Advanced Settings
          </Button>
        </div>

        {showAdvanced && (
          <div className="space-y-4 p-4 border rounded-lg bg-muted/50">
            <h4 className="font-medium text-sm">Advanced Connection Settings</h4>
            <div className="grid grid-cols-1 gap-4">
              <div className="space-y-2">
                <Label htmlFor="connectTimeout">Connection Timeout (ms)</Label>
                <Input
                  id="connectTimeout"
                  type="number"
                  value={config.connectTimeout}
                  onChange={(e) => setConfig({ ...config, connectTimeout: Number.parseInt(e.target.value) || 10000 })}
                  placeholder="10000"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="commandTimeout">Command Timeout (ms)</Label>
                <Input
                  id="commandTimeout"
                  type="number"
                  value={config.commandTimeout}
                  onChange={(e) => setConfig({ ...config, commandTimeout: Number.parseInt(e.target.value) || 5000 })}
                  placeholder="5000"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="maxRetries">Max Retries Per Request</Label>
                <Input
                  id="maxRetries"
                  type="number"
                  value={config.maxRetriesPerRequest}
                  onChange={(e) => setConfig({ ...config, maxRetriesPerRequest: Number.parseInt(e.target.value) || 5 })}
                  placeholder="5"
                />
              </div>
            </div>
          </div>
        )}

        <div className="flex items-center space-x-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={generateUri}
            className="flex items-center gap-2"
          >
            <Link className="w-4 h-4" />
            Generate URI
          </Button>
        </div>
          </TabsContent>

          <TabsContent value="uri" className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="connectionUri">Redis Connection URI</Label>
              <div className="flex space-x-2">
                <Input
                  id="connectionUri"
                  value={connectionUri}
                  onChange={(e) => setConnectionUri(e.target.value)}
                  placeholder="redis://username:password@host:port/database or rediss://..."
                  className="flex-1"
                />
                {connectionUri && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={copyUri}
                    className="flex items-center gap-2"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                )}
              </div>
            </div>

            {!connectionName && connectionUri && (
              <div className="text-xs text-muted-foreground bg-muted/50 p-2 rounded border-l-2 border-blue-500">
                <div className="flex items-center gap-1">
                  <Info className="w-3 h-3" />
                  <span className="font-medium">Auto-generated name:</span>
                </div>
                <div className="mt-1 font-mono text-blue-600 dark:text-blue-400">
                  {getAutoGeneratedName()}
                </div>
              </div>
            )}

            <Alert>
              <Info className="h-4 w-4" />
              <AlertDescription>
                <div className="space-y-2">
                  <p className="font-medium">URI Format Examples:</p>
                  <div className="text-sm space-y-1 font-mono">
                    <p>• <strong>Basic:</strong> redis://localhost:6379</p>
                    <p>• <strong>With Auth:</strong> redis://username:password@host:6379</p>
                    <p>• <strong>With TLS:</strong> rediss://username:password@host:6380</p>
                    <p>• <strong>With Database:</strong> redis://host:6379/1</p>
                    <p>• <strong>Cloud Provider:</strong> rediss://user:pass@aiven-host:port</p>
                  </div>
                </div>
              </AlertDescription>
            </Alert>
          </TabsContent>
        </Tabs>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <div className="space-y-3">
                <div>
                  <p className="font-semibold text-sm">{detailedError?.title || "Connection Error"}</p>
                  <p className="text-sm mt-1">{error}</p>
                </div>
                
                {detailedError?.suggestions && (
                  <div className="text-sm space-y-2">
                    <p className="font-medium">Try these solutions:</p>
                    <ul className="list-disc list-inside space-y-1 text-xs">
                      {detailedError.suggestions.map((suggestion: string, index: number) => (
                        <li key={index}>{suggestion}</li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="mt-3 p-2 bg-muted rounded text-xs">
                  <p className="font-medium">Quick test:</p>
                  <p>Run <code className="bg-background px-1 rounded">redis-cli -h {config.host} -p {config.port} ping</code> in terminal</p>
                  <p>Should return: <code className="bg-background px-1 rounded">PONG</code></p>
                </div>

                {detailedError?.technicalDetails && (
                  <details className="mt-2">
                    <summary className="text-xs cursor-pointer hover:text-foreground">Show technical details</summary>
                    <p className="text-xs mt-1 font-mono bg-muted p-2 rounded break-all">
                      {detailedError.technicalDetails}
                    </p>
                  </details>
                )}
              </div>
            </AlertDescription>
          </Alert>
        )}

        <Button 
          onClick={handleConnect} 
          disabled={isConnecting || (connectionMethod === "form" ? !config.host : !connectionUri)} 
          className="w-full"
        >
          {isConnecting ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Connecting...
            </>
          ) : (
            "Connect to Redis"
          )}
        </Button>

        {/* Connection Help Alert */}
        <Alert>
          <Info className="h-4 w-4" />
          <AlertDescription>
            <div className="space-y-2">
              <p className="font-medium">Connection Requirements</p>
              <div className="text-sm space-y-1">
                <p>• <strong>Remote Redis Only:</strong> This app can only connect to Redis servers accessible from the internet</p>
                <p>• <strong>Public IP/Domain:</strong> Use your Redis server's public IP or domain name</p>
                <p>• <strong>Cloud Providers:</strong> Enable TLS/SSL for services like Aiven, Redis Cloud, AWS ElastiCache</p>
                <p>• <strong>Local Redis:</strong> Not supported - browsers block local network access for security</p>
                <p>• <strong>Self-hosted:</strong> Run this app locally to connect to local Redis instances</p>
              </div>
            </div>
          </AlertDescription>
        </Alert>
      </CardContent>
    </Card>
  )
}
