"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogHeader, 
  DialogTitle 
} from "@/components/ui/dialog"
import { 
  Database, 
  Server, 
  Activity, 
  Users, 
  Lock, 
  Shield, 
  Settings, 
  Info, 
  Link, 
  Copy, 
  AlertCircle, 
  CheckCircle, 
  Key, 
  Eye, 
  EyeOff, 
  ChevronRight, 
  ChevronLeft,
  Sparkles
} from "lucide-react"
import { buildRedisUri, generateConnectionName, type RedisConfig } from "@/lib/redis-uri"
import { validatePassphrase, generateSecurePassphrase } from "@/lib/connection-encryption"

interface CreateProfileWizardProps {
  isOpen: boolean
  onClose: () => void
  onComplete: (config: RedisConfig, connectionName: string, passphrase: string) => Promise<void>
  isUnlocked: boolean
  initialConfig?: RedisConfig
  initialName?: string
  mode?: 'create' | 'edit'
}

export function CreateProfileWizard({
  isOpen,
  onClose,
  onComplete,
  isUnlocked,
  initialConfig,
  initialName = "",
  mode = 'create'
}: CreateProfileWizardProps) {
  // Step management
  const [currentStep, setCurrentStep] = useState(1)
  const totalSteps = isUnlocked && mode === 'edit' ? 1 : 2

  // Connection Config State
  const [config, setConfig] = useState<RedisConfig>(initialConfig || {
    host: "localhost",
    port: 6379,
    username: "",
    password: "",
    database: 0,
    tls: false,
    connectTimeout: 10000,
    commandTimeout: 5000,
    maxRetriesPerRequest: 5,
  })
  const [connectionName, setConnectionName] = useState(initialName)
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [connectionUri, setConnectionUri] = useState(() => {
    if (initialConfig) {
      if ('uri' in initialConfig && initialConfig.uri) {
        return initialConfig.uri as string
      }
      try {
        return buildRedisUri(initialConfig)
      } catch {
        return ""
      }
    }
    return ""
  })
  const [connectionMethod, setConnectionMethod] = useState<"form" | "uri">(() => {
    if (initialConfig && 'uri' in initialConfig && initialConfig.uri) {
      return "uri"
    }
    return "form"
  })

  // Passphrase State
  const [passphrase, setPassphrase] = useState("")
  const [confirmPassphrase, setConfirmPassphrase] = useState("")
  const [showPassphrase, setShowPassphrase] = useState(false)
  const [showConfirmPassphrase, setShowConfirmPassphrase] = useState(false)
  const [passphraseValidation, setPassphraseValidation] = useState<{ isValid: boolean; errors: string[] }>({ 
    isValid: true, 
    errors: [] 
  })

  // Other State
  const [isProcessing, setIsProcessing] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Reset state when dialog opens/closes
  useEffect(() => {
    if (isOpen) {
      setCurrentStep(1)
      setPassphrase("")
      setConfirmPassphrase("")
      setShowPassphrase(false)
      setShowConfirmPassphrase(false)
      setPassphraseValidation({ isValid: true, errors: [] })
      setError(null)
      setIsProcessing(false)
    }
  }, [isOpen])

  // Validate passphrase in real-time
  useEffect(() => {
    if (passphrase && currentStep === 2 && !isUnlocked) {
      setPassphraseValidation(validatePassphrase(passphrase))
    } else {
      setPassphraseValidation({ isValid: true, errors: [] })
    }
  }, [passphrase, currentStep, isUnlocked])

  const getAutoGeneratedName = () => {
    if (connectionMethod === "uri" && connectionUri) {
      try {
        const url = new URL(connectionUri)
        const uriConfig: RedisConfig = {
          host: url.hostname,
          port: parseInt(url.port) || (url.protocol === 'rediss:' ? 6380 : 6379),
          tls: url.protocol === 'rediss:',
          username: url.username || undefined,
          password: url.password || undefined,
          database: url.pathname && url.pathname !== '/' ? parseInt(url.pathname.slice(1)) : undefined,
        }
        return generateConnectionName(uriConfig)
      } catch (error) {
        const match = connectionUri.match(/(?:redis[s]?:\/\/)?(?:[^@]+@)?([^:\/]+)/)
        if (match && match[1]) {
          return `${match[1]} Redis`
        }
        return "Redis Connection"
      }
    }
    return generateConnectionName(config)
  }

  const generateUri = () => {
    try {
      const uri = buildRedisUri(config)
      setConnectionUri(uri)
      setConnectionMethod("uri")
    } catch (error) {
      setError("Failed to generate URI: " + (error instanceof Error ? error.message : "Unknown error"))
    }
  }

  const copyUri = async () => {
    try {
      await navigator.clipboard.writeText(connectionUri)
    } catch (error) {
      console.error("Failed to copy URI:", error)
    }
  }

  const handleGeneratePassphrase = () => {
    const generated = generateSecurePassphrase()
    setPassphrase(generated)
    setConfirmPassphrase(generated)
    setPassphraseValidation(validatePassphrase(generated))
  }

  const isStep1Valid = () => {
    if (connectionMethod === "form") {
      return config.host && config.port
    }
    return connectionUri.length > 0
  }

  const isStep2Valid = () => {
    if (isUnlocked) return true
    return (
      passphraseValidation.isValid && 
      passphrase === confirmPassphrase && 
      passphrase.length >= 8
    )
  }

  const handleNext = () => {
    if (currentStep === 1 && isStep1Valid()) {
      if (totalSteps === 1) {
        // If editing and unlocked, skip to submit
        handleSubmit()
      } else {
        setCurrentStep(2)
      }
    }
  }

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1)
      setError(null)
    }
  }

  const handleSubmit = async () => {
    setIsProcessing(true)
    setError(null)

    try {
      const finalConfig = connectionMethod === "uri" 
        ? { uri: connectionUri } as any 
        : config
      
      const finalName = connectionName || getAutoGeneratedName()
      
      await onComplete(finalConfig, finalName, passphrase)
      onClose()
    } catch (error) {
      setError(error instanceof Error ? error.message : "Failed to save profile")
    } finally {
      setIsProcessing(false)
    }
  }

  const renderStepIndicator = () => (
    <div className="mb-6">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <div className={`flex items-center justify-center w-8 h-8 rounded-full ${
            currentStep >= 1 ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
          }`}>
            {currentStep > 1 ? <CheckCircle className="w-4 h-4" /> : '1'}
          </div>
          <span className={`text-sm font-medium ${currentStep >= 1 ? 'text-foreground' : 'text-muted-foreground'}`}>
            Connection Details
          </span>
        </div>

        {totalSteps > 1 && (
          <>
            <ChevronRight className="w-4 h-4 text-muted-foreground" />
            
            <div className="flex items-center gap-2">
              <div className={`flex items-center justify-center w-8 h-8 rounded-full ${
                currentStep >= 2 ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
              }`}>
                {currentStep > 2 ? <CheckCircle className="w-4 h-4" /> : '2'}
              </div>
              <span className={`text-sm font-medium ${currentStep >= 2 ? 'text-foreground' : 'text-muted-foreground'}`}>
                {isUnlocked ? 'Review' : 'Passphrase'}
              </span>
            </div>
          </>
        )}
      </div>
      <Progress value={(currentStep / totalSteps) * 100} className="h-2" />
    </div>
  )

  const renderStep1 = () => (
    <div className="space-y-6">
      {/* Connection Name */}
      <div className="space-y-3">
        <div className="flex items-center gap-2">
          <div className="p-1 rounded bg-blue-100 dark:bg-blue-900/30">
            <Settings className="w-4 h-4 text-blue-600 dark:text-blue-400" />
          </div>
          <Label htmlFor="connectionName" className="text-sm font-medium">Connection Name</Label>
          <Badge variant="secondary" className="text-xs">Optional</Badge>
        </div>
        <Input
          id="connectionName"
          value={connectionName}
          onChange={(e) => setConnectionName(e.target.value)}
          placeholder="My Redis Server"
          className="h-11"
        />
        {!connectionName && ((config.host || config.port) || (connectionMethod === "uri" && connectionUri)) && (
          <div className="text-xs text-muted-foreground bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950/30 dark:to-indigo-950/30 p-3 rounded-lg border border-blue-200 dark:border-blue-800">
            <div className="flex items-center gap-2">
              <div className="p-1 rounded-full bg-blue-100 dark:bg-blue-900/50">
                <Info className="w-3 h-3 text-blue-600 dark:text-blue-400" />
              </div>
              <span className="font-medium">Auto-generated name:</span>
            </div>
            <div className="mt-2 font-mono text-blue-700 dark:text-blue-300 bg-white dark:bg-gray-800 px-2 py-1 rounded border">
              {getAutoGeneratedName()}
            </div>
          </div>
        )}
      </div>

      {/* Connection Method Tabs */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <div className="p-1 rounded bg-green-100 dark:bg-green-900/30">
            <Server className="w-4 h-4 text-green-600 dark:text-green-400" />
          </div>
          <Label className="text-sm font-medium">Connection Method</Label>
        </div>
        
        <Tabs value={connectionMethod} onValueChange={(value) => setConnectionMethod(value as "form" | "uri")}>
          <TabsList className="grid w-full grid-cols-2 gap-2 h-12 p-2">
            <TabsTrigger value="form" className="flex items-center gap-2">
              <Settings className="w-4 h-4" />
              Form
            </TabsTrigger>
            <TabsTrigger value="uri" className="flex items-center gap-2">
              <Link className="w-4 h-4" />
              URI
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="form" className="space-y-6 mt-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Host Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-orange-100 dark:bg-orange-900/30">
                    <Server className="w-4 h-4 text-orange-600 dark:text-orange-400" />
                  </div>
                  <Label htmlFor="host" className="text-sm font-medium">Host</Label>
                  <Badge variant="destructive" className="text-xs">Required</Badge>
                </div>
                <Input
                  id="host"
                  value={config.host}
                  onChange={(e) => setConfig({ ...config, host: e.target.value })}
                  placeholder="your-redis-server.com"
                  className="h-11"
                />
              </div>
              
              {/* Port Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-purple-100 dark:bg-purple-900/30">
                    <Activity className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                  </div>
                  <Label htmlFor="port" className="text-sm font-medium">Port</Label>
                  <Badge variant="destructive" className="text-xs">Required</Badge>
                </div>
                <Input
                  id="port"
                  type="number"
                  value={config.port}
                  onChange={(e) => setConfig({ ...config, port: Number.parseInt(e.target.value) || 6379 })}
                  placeholder="6379"
                  className="h-11"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Username Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-blue-100 dark:bg-blue-900/30">
                    <Users className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                  </div>
                  <Label htmlFor="username" className="text-sm font-medium">Username</Label>
                  <Badge variant="secondary" className="text-xs">Optional</Badge>
                </div>
                <Input
                  id="username"
                  value={config.username}
                  onChange={(e) => setConfig({ ...config, username: e.target.value })}
                  placeholder="Enter username if required"
                  className="h-11"
                />
              </div>
              
              {/* Password Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-red-100 dark:bg-red-900/30">
                    <Lock className="w-4 h-4 text-red-600 dark:text-red-400" />
                  </div>
                  <Label htmlFor="password" className="text-sm font-medium">Password</Label>
                  <Badge variant="secondary" className="text-xs">Optional</Badge>
                </div>
                <Input
                  id="password"
                  type="password"
                  value={config.password}
                  onChange={(e) => setConfig({ ...config, password: e.target.value })}
                  placeholder="Enter password if required"
                  className="h-11"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Database Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-green-100 dark:bg-green-900/30">
                    <Database className="w-4 h-4 text-green-600 dark:text-green-400" />
                  </div>
                  <Label htmlFor="database" className="text-sm font-medium">Database</Label>
                  <Badge variant="outline" className="text-xs">Default: 0</Badge>
                </div>
                <Input
                  id="database"
                  type="number"
                  value={config.database}
                  onChange={(e) => setConfig({ ...config, database: Number.parseInt(e.target.value) || 0 })}
                  placeholder="0"
                  className="h-11"
                />
              </div>
              
              {/* TLS Field */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded bg-yellow-100 dark:bg-yellow-900/30">
                    <Shield className="w-4 h-4 text-yellow-600 dark:text-yellow-400" />
                  </div>
                  <Label htmlFor="tls" className="text-sm font-medium">TLS/SSL</Label>
                  <Badge variant="outline" className="text-xs">Security</Badge>
                </div>
                <div className="flex items-center space-x-3 p-3 rounded-lg border bg-muted/30">
                  <Switch
                    id="tls"
                    checked={config.tls || false}
                    onCheckedChange={(checked) => setConfig({ ...config, tls: checked })}
                  />
                  <div className="flex-1">
                    <Label htmlFor="tls" className="text-sm font-medium">
                      {config.tls ? "Encrypted Connection" : "Unencrypted Connection"}
                    </Label>
                    <p className="text-xs text-muted-foreground">
                      {config.tls ? "Data is encrypted in transit" : "Data is sent in plain text"}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Advanced Settings */}
            <div className="space-y-4">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="flex items-center gap-2"
              >
                <Settings className="w-4 h-4" />
                {showAdvanced ? "Hide" : "Show"} Advanced Settings
              </Button>
            </div>

            {showAdvanced && (
              <div className="space-y-4 p-4 border rounded-lg bg-muted/50">
                <h4 className="font-medium text-sm">Advanced Connection Settings</h4>
                <div className="grid grid-cols-1 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="connectTimeout">Connection Timeout (ms)</Label>
                    <Input
                      id="connectTimeout"
                      type="number"
                      value={config.connectTimeout}
                      onChange={(e) => setConfig({ ...config, connectTimeout: Number.parseInt(e.target.value) || 10000 })}
                      placeholder="10000"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="commandTimeout">Command Timeout (ms)</Label>
                    <Input
                      id="commandTimeout"
                      type="number"
                      value={config.commandTimeout}
                      onChange={(e) => setConfig({ ...config, commandTimeout: Number.parseInt(e.target.value) || 5000 })}
                      placeholder="5000"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="maxRetries">Max Retries Per Request</Label>
                    <Input
                      id="maxRetries"
                      type="number"
                      value={config.maxRetriesPerRequest}
                      onChange={(e) => setConfig({ ...config, maxRetriesPerRequest: Number.parseInt(e.target.value) || 5 })}
                      placeholder="5"
                    />
                  </div>
                </div>
              </div>
            )}

            {/* Generate URI Button */}
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={generateUri}
              className="flex items-center gap-2"
            >
              <Link className="w-4 h-4" />
              Generate URI
            </Button>
          </TabsContent>

          <TabsContent value="uri" className="space-y-6 mt-6">
            {/* URI Input */}
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <div className="p-1 rounded bg-indigo-100 dark:bg-indigo-900/30">
                  <Link className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                </div>
                <Label htmlFor="connectionUri" className="text-sm font-medium">Redis Connection URI</Label>
                <Badge variant="destructive" className="text-xs">Required</Badge>
              </div>
              <div className="flex space-x-2">
                <Input
                  id="connectionUri"
                  value={connectionUri}
                  onChange={(e) => setConnectionUri(e.target.value)}
                  placeholder="redis://username:password@host:port/database"
                  className="flex-1 h-11"
                />
                {connectionUri && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={copyUri}
                    className="h-11 px-3"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                )}
              </div>
            </div>

            <Alert>
              <Info className="h-4 w-4" />
              <AlertDescription>
                <div className="space-y-2">
                  <p className="font-medium">URI Format Examples:</p>
                  <div className="text-sm space-y-1 font-mono">
                    <p>• redis://localhost:6379</p>
                    <p>• redis://username:password@host:6379</p>
                    <p>• rediss://username:password@host:6380</p>
                  </div>
                </div>
              </AlertDescription>
            </Alert>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )

  const renderStep2 = () => (
    <div className="space-y-6">
      <Alert>
        <Shield className="h-4 w-4" />
        <AlertDescription>
          {isUnlocked 
            ? "Your profile will be encrypted with your current passphrase."
            : "Create a secure passphrase to encrypt your connection profile. This passphrase will be required every time you reload the application."
          }
        </AlertDescription>
      </Alert>

      {!isUnlocked && (
        <>
          {/* Passphrase Input */}
          <div className="space-y-3">
            <Label htmlFor="passphrase" className="flex items-center gap-2">
              <Lock className="w-4 h-4" />
              Passphrase
            </Label>
            <div className="relative">
              <Input
                id="passphrase"
                type={showPassphrase ? "text" : "password"}
                value={passphrase}
                onChange={(e) => setPassphrase(e.target.value)}
                placeholder="Enter your passphrase"
                className="pr-10 h-11"
                autoComplete="new-password"
                required
              />
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                onClick={() => setShowPassphrase(!showPassphrase)}
              >
                {showPassphrase ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          {/* Confirm Passphrase */}
          <div className="space-y-3">
            <Label htmlFor="confirmPassphrase" className="flex items-center gap-2">
              <Lock className="w-4 h-4" />
              Confirm Passphrase
            </Label>
            <div className="relative">
              <Input
                id="confirmPassphrase"
                type={showConfirmPassphrase ? "text" : "password"}
                value={confirmPassphrase}
                onChange={(e) => setConfirmPassphrase(e.target.value)}
                placeholder="Confirm your passphrase"
                className="pr-10 h-11"
                autoComplete="new-password"
                required
              />
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                onClick={() => setShowConfirmPassphrase(!showConfirmPassphrase)}
              >
                {showConfirmPassphrase ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          {/* Passphrase Validation */}
          {passphrase && (
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm">
                <Key className="w-4 h-4" />
                <span className="font-medium">Passphrase Strength:</span>
                {passphraseValidation.isValid && passphrase === confirmPassphrase ? (
                  <CheckCircle className="w-4 h-4 text-green-500" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-red-500" />
                )}
              </div>
              
              {passphraseValidation.errors.length > 0 && (
                <div className="space-y-1">
                  {passphraseValidation.errors.map((error, index) => (
                    <div key={index} className="flex items-center gap-2 text-sm text-red-600">
                      <AlertCircle className="w-3 h-3" />
                      {error}
                    </div>
                  ))}
                </div>
              )}

              {passphraseValidation.isValid && passphrase !== confirmPassphrase && confirmPassphrase && (
                <div className="flex items-center gap-2 text-sm text-red-600">
                  <AlertCircle className="w-3 h-3" />
                  Passphrases do not match
                </div>
              )}
            </div>
          )}

          {/* Generate Passphrase */}
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleGeneratePassphrase}
            className="w-full"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            Generate Secure Passphrase
          </Button>

          {/* Security Info */}
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription className="text-sm">
              <strong>Security Note:</strong> Your passphrase is never stored. All encryption/decryption happens locally in your browser.
            </AlertDescription>
          </Alert>
        </>
      )}
    </div>
  )

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-primary" />
            {mode === 'edit' ? 'Edit Profile' : 'Create Encrypted Profile'}
          </DialogTitle>
          <DialogDescription>
            {mode === 'edit' 
              ? 'Update your encrypted connection profile.'
              : 'Create a new encrypted connection profile with step-by-step guidance.'
            }
          </DialogDescription>
        </DialogHeader>

        {renderStepIndicator()}

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        <div className="space-y-6">
          {currentStep === 1 && renderStep1()}
          {currentStep === 2 && renderStep2()}
        </div>

        {/* Navigation Buttons */}
        <div className="flex justify-between pt-6 border-t">
          <Button
            variant="outline"
            onClick={currentStep === 1 ? onClose : handleBack}
            disabled={isProcessing}
          >
            {currentStep === 1 ? (
              "Cancel"
            ) : (
              <>
                <ChevronLeft className="w-4 h-4 mr-2" />
                Back
              </>
            )}
          </Button>

          <Button
            onClick={currentStep === totalSteps ? handleSubmit : handleNext}
            disabled={
              isProcessing || 
              (currentStep === 1 && !isStep1Valid()) ||
              (currentStep === 2 && !isStep2Valid())
            }
          >
            {isProcessing ? (
              <>
                <div className="w-4 h-4 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin mr-2" />
                {mode === 'edit' ? 'Updating...' : 'Creating...'}
              </>
            ) : currentStep === totalSteps ? (
              <>
                <CheckCircle className="w-4 h-4 mr-2" />
                {mode === 'edit' ? 'Update Profile' : 'Create Profile'}
              </>
            ) : (
              <>
                Next
                <ChevronRight className="w-4 h-4 ml-2" />
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

